### ISSUE TITLE
wikilink.ftplugin no longer working after upgrade to 10.10.4

### ISSUE THREAD

**Issue by ryan-p-randall** [jamiekowalski/foldingtext-extra#2]
Hi Jamie, 

Do you know if 10.10.4 introduced any changes that would break the wikilink.ftplugin? It was working fine earlier today before I upgraded, and now suspiciously will not even though I'm clicking on the same links in the same files.  

Thanks for the many times I used the plug-in, even if it's no longer supportable after the upgrade (although I sure hope it is). 

Ryan

**Comment by RobTrew** [comment]
Have you tried re-registering the ftwikilink:// url scheme by running `Handle FoldingText WikiLinks.app` in the plugin folder ?

**Comment by ryan-p-randall** [comment]
Thank you, that fixed it!

False alarm on it being an upgrade bug, everyone. ;^)

Best,
Ryan
